### PR TITLE
Add missing maps and event quests

### PR DESCRIPTION
**Pull request by gakada**
Quest translations are from Wikia.

### CODE REVIEW

**Comment by Yuubari** [comment]
The event quests will have to be removed afterwards, though, as their IDs will be most probably reused like it happened a few times before…

**Comment by gakada** [comment]
Might as well remove event maps then (e.g. [E2](http://wikiwiki.jp/kancolle/?%C8%AF%CE%E1%A1%AA%C2%E8%BD%BD%B0%EC%B9%E6%BA%EE%C0%EF#area2), [E4](http://wikiwiki.jp/kancolle/?%C8%AF%CE%E1%A1%AA%C2%E8%BD%BD%B0%EC%B9%E6%BA%EE%C0%EF#area4), [4-5](http://wikiwiki.jp/kancolle/?%C0%BE%CA%FD%B3%A4%B0%E8#area5) all have the same name).

**Comment by Yuubari** [comment]
Well, that's for once the event is over.

**Comment by gakada** [comment]
Yeah, I mean afterwards, just in case (it's E2 and E4 from the previous event, 4-5 is like a remake of them, the current event maps are unique currently).

**Pull request merged**
