### PR TITLE
changed CLp to CT

### PR DESCRIPTION
**Pull request by paterk**

### CODE REVIEW

**Comment by Yuubari** [comment]
Why?

**Comment by paterk** [comment]
i believe that the english community has agreed to changed it to CT
http://kancolle.wikia.com/wiki/Elitecl
http://en.kancollewiki.net/wiki/Talk:Katori/@comment-Nukurin-20150207221416/@comment-Ethrundr-20150208002851

**Comment by Yuubari** [comment]
I believe that 1) Wikia does not represent the entire English-speaking community; 2) a single comment on a discussion page does not represent the entire English-speaking community.

**Comment by paterk** [comment]
right. im sorry for that.

**Pull request closed without merging**
