### PR TITLE
A new Chinese version

### PR DESCRIPTION
**Pull request by AnnaKutou**
I make this version with my friend. Hope they can be released.

### CODE REVIEW

**Comment by KyoriAsh** [comment]
Regarding ShipTypes, I suggest to follow how JA version did, instead of adding ShipType Code in front of Chinese wording.

**Comment by AnnaKutou** [comment]
Thank you for your suggestion. But I'm sorry about I may not change it.
In fact, I considered this before translating, and I still added Shiptype code. Because that, as far as I know, a great number of Chinese Teitoku are used to Shiptype code instead of JA.ver even CH.ver when they communicate with each other. New Chinese Tetoku may get help from this.

**Comment by c933103** [comment]
Just that Superdreadnought's B isn't even a code..

**Comment by Yuubari** [comment]
Closing this PR due to being insanely outdated.

**Pull request closed without merging**
