### PR TITLE
Some (mainly quests) changes

### PR DESCRIPTION
**Pull request by gakada**
Also

* There are some changes going on with equipment translations on Wikia ([1](http://kancolle.wikia.com/wiki/Sandbox/EquipmentListKai), [2](http://kancolle.wikia.com/wiki/Thread:206780#275)), what do you think about following them?
* AFAIK not everything is translated in Operations.xml, but I think that having a module that can map from API to node labels (from wiki, A, B, C, etc., like in 5-4-A) would be better, so that these labels can be used in Logger, Overview (i.e. to show the current node when in sortie), etc., maybe leaving translations as an optional addition.

### CODE REVIEW

**Comment by Yuubari** [comment]
Can you provide a rationale for “FBB”?

**Comment by gakada** [comment]
1) Isn't it a [common](http://kancolle.wikia.com/wiki/Glossary#Class_classification) term in the game community? (not [historically](https://en.wikipedia.org/wiki/Fast_battleship#World_War_II_designs) of course, but in the game BB and BBV are "slow", while Fast BB are, well, "fast"), 2) all ship types are codes in ShipTypes.xml, except "Fast BB" that uses the word "fast", 3) I want to explicitly specify classes in quest descriptions, so FBB/BB for "battleship, BBV don't count" or BB/BBV for "slow battleship" (no FBB here). So not really an important thing, just used it as a somewhat shorter variant for "Fast BB" that is also known.

**Comment by Yuubari** [comment]
I'd rather leave it as is.

Also, removing exclamation marks in quest titles was a conscious decision, not an omission/error. Why do you want to re-introduce them?

**Comment by gakada** [comment]
Quite a few titles still have them [here](https://github.com/KCV-Localisation/KanColleViewer-Translations/blob/master/Quests.xml), do you want me to remove all exclamation marks?

**Comment by Yuubari** [comment]
That would be pretty nice. I wanted to get around to it but I constantly get distracted by other things (like re-implementing translations in 4.x right now, for example).

**Comment by gakada** [comment]
As an off-topic (but related to translations), [TranslationsPath](https://github.com/Yuubari/KanColleViewer/blob/translation/source/Grabacr07.KanColleWrapper/Translations.cs), but there is also [mainFolder](https://github.com/Yuubari/LegacyKCV/blob/master/Grabacr07.KanColleWrapper/Logger.cs), so I guess it's possible to make a `public static readonly string` field in [KanColleClient](https://github.com/Grabacr07/KanColleViewer/blob/develop/source/Grabacr07.KanColleWrapper/KanColleClient.cs) using `Path.GetDirectoryName(Assembly.GetEntryAssembly().Location)` and use it everywhere (Logger, Translations), this should resolve [those](https://github.com/Yuubari/LegacyKCV/blob/master/FAQ.md#i-pinned-kcv-to-my-taskbar-and-translations-arent-working) problems (it worked for me).

**Comment by Yuubari** [comment]
That's already done in the newest code revision. The translations branch is very, very work in progress and I'm iterating through different approaches every day.

Currently it's
```C#
var workingDirectory = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location) ?? "";
translationsPath = Path.Combine(workingDirectory, "Translations");
```

**Comment by Yuubari** [comment]
Merged this just now; I've restored exclamation marks in the quest titles that are direct speech and corrected some titles to read/sound better.

**Pull request merged**
