### PR TITLE
Add expedition translations

### PR DESCRIPTION
**Pull request by gakada**
From yuyuvn's KCV

### CODE REVIEW

**Comment by Yuubari** [comment]
As was already mentioned before, Zharay's fork never supported expedition translations, it's a feature of yuyuvn's fork if I recall correctly.

I'm also unsure if adding support for them is worth it as it really does not provide any really useful information (expedition information is only shown when a fleet is already sortied on an expedition).

**Comment by gakada** [comment]
Original KCV displays these titles and descriptions for expeditions in Japanese, so I think localized version should provide translations, though I agree that Japanese or not they are not really useful, my main motivation is that I'm switching to a KCV-Localisation/KanColleViewer-Translations submodule in my fork.

**Comment by Yuubari** [comment]
It may be worth it to actually translate the titles, then, adding the number (if it's really needed) in front of the title.

I'm planning to do that with the quests too, since, for example, “Daily Sortie 1” is not that great. The planned format is “Bd1: Defeat an Enemy Fleet!”.

**Comment by gakada** [comment]
Currently:

    <Expedition>
      <ID>1</ID>
      <JP-Name>練習航海</JP-Name>
      <TR-Name>Expedition 1</TR-Name>
      <JP-Detail>鎮守府近海を航海し、艦隊の練度を高めよう！</JP-Detail>
      <TR-Detail>Practice Voyage: Sail around the Naval District to improve the skills of our fleet! (This mission will not yield any bonus rewards)</TR-Detail>
    </Expedition>

it uses expedition numbers in TR-Name instead of translations for JP-Name, while TR-Detail have both title and description (JP-Name and JP-Detail) translations in it (with notes about expeditions without bonus rewards). The layout is the same as in original KCV:



For quests I'm using



You want to change the layout for quests to one line Code: Hints (not really a translation usually)?

**Comment by Yuubari** [comment]
Nah, I only mean the titles, not the descriptions. Instructions instead of descriptions for quests are good enough.

**Pull request merged**
